server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/test
    username: postgres
    password: postgres
  jpa:
    open-in-view: on
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:db/changelog/master-changelog.yaml